### PR TITLE
Derive the --package-root options.

### PR DESCRIPTION
**Pull request by thundergolfer**
Pulls across some of @josh-newman's changes from https://github.com/thundergolfer/bazel-mypy-integration/pull/12. Also should address #15 

Fixes the following error message: `darwin-fastbuild is not a valid Python package name` which occurs when included generated sources (eg. protobuf) in a `py_` target.

----

cc @dmadisetti

### CODE REVIEW

**Comment by thundergolfer** [comment]
The generated protobuf code still causes errors: 

```
Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/darwin-fastbuild/bin/proto/person_pb2.py:18: error: Unexpected keyword argument "serialized_options" for "FileDescriptor"; did you mean "serialized_pb"?
bazel-out/host/bin/external/mypy_integration/mypy/mypy.runfiles/mypy_integration_pip_deps_pypi__mypy_0_760/mypy/typeshed/third_party/2and3/google/protobuf/descriptor.pyi:279: note: "FileDescriptor" defined here
bazel-out/darwin-fastbuild/bin/proto/person_pb2.py:36: error: Unexpected keyword argument "serialized_options" for "FieldDescriptor"
bazel-out/host/bin/external/mypy_integration/mypy/mypy.runfiles/mypy_integration_pip_deps_pypi__mypy_0_760/mypy/typeshed/third_party/2and3/google/protobuf/descriptor.pyi:168: note: "FieldDescriptor" defined here
bazel-out/darwin-fastbuild/bin/proto/person_pb2.py:36: error: Unexpected keyword argument "json_name" for "FieldDescriptor"
bazel-out/host/bin/external/mypy_integration/mypy/mypy.runfiles/mypy_integration_pip_deps_pypi__mypy_0_760/mypy/typeshed/third_party/2and3/google/protobuf/descriptor.pyi:168: note: "FieldDescriptor" defined here
...
```

the root cause of which is that the gen'd code keeps using the `serialized_options` keyword even though the [Typeshed types don't recognise that keyword](https://github.com/python/typeshed/blob/master/third_party/2and3/google/protobuf/descriptor.pyi).

**Comment by josh-newman** [comment]
Thanks, this looks good. I got pulled away to some other work, so I may have to return to #12 a bit later.

**Comment by thundergolfer** [comment]
No worries. I'll merge this and then look at the Protobuf typecheck errors sometime in the future.

I'm hoping there's a way to generate the code without the `serialized_options` keyword, as it's deprecated anyway.

**Comment by thundergolfer** [comment]
This has create a regression in some code that was working on `0.0.7`. I have a target `//foo/storage:sync` like: 

```
py_binary(
    name = "sync",
    srcs = ["sync.py"],
    deps = [
        "//foo/types",
        requirement("boto3"),
        requirement("loguru"),
    ],
    python_version = "PY3",
    visibility = [
        "//visibility:public",
    ]
)
```

and trying to `build` I get: 

```
Use --sandbox_debug to see verbose messages from the sandbox
rememex/storage/sync.py:12: error: Cannot find implementation or library stub for module named 'rememex.types'
rememex/storage/sync.py:12: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

**Comment by dmadisetti** [comment]
Thanks for tagging me in this. I have not been synced with head. Current changes do break my code now 😢 , but I'm sure we'll work out something. I'll sync https://github.com/thundergolfer/bazel-python-mypy-protobuf with 0.10.0 sometime this week. Do you have a reproducible case for the breakage in 0.7.0?

**Comment by thundergolfer** [comment]
>  Current changes do break my code now 😢

Oh damn. 😢 

A regression test would be great. I've added your previous regression tests but they clearly aren't adequate.

On my side things appear to be working fine with `py_proto_library` after I apply the bandaid mentioned here https://github.com/thundergolfer/bazel-mypy-integration/issues/21
